name: 'Check'
description: 'CI check'
runs:
    using: 'composite'
    steps:
        -   uses: actions/checkout@v2
        -   uses: oven-sh/setup-bun@v1
        -   run: bun install
        -   run: bun lint
        -   run: bun check