name: Check
on:
    workflow_dispatch:
    push:
    pull_request:
    create:
jobs:
    check:
        name: Check
        runs-on: ubuntu-latest
        steps:
            -   uses: ./.github/actions/check