name: Check
on:
    workflow_dispatch:
    push:
    pull_request:
    create:
jobs:
    check:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   uses: ./.github/actions/check