name: Deploy
concurrency:
    group: deploy
    cancel-in-progress: true
on:
    workflow_dispatch:
    push:
        branches:
            - master
jobs:
    check:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: ./.github/actions/check
    deploy:
        needs: check
        runs-on: ubuntu-latest
        environment: production
        env:
            CF_DISTRIBUTION_ID: ESK99ORO9Y70O
            BUCKET: aaronmamparo.com
        steps:
            - uses: actions/checkout@v2
            - uses: aws-actions/configure-aws-credentials@v1
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: us-east-1
            - uses: oven-sh/setup-bun@v1
            - run: bun install
            - run: bun run build
            - run: bun deploy:stack
            - name: Upload to S3
              run: aws s3 sync build "s3://${BUCKET}" --delete
            - name: Clear cloudfront cache
              run: aws cloudfront create-invalidation --distribution-id "${CF_DISTRIBUTION_ID}" --paths "/*"
